### ISSUE TITLE
melainkan

### ISSUE THREAD

**Issue by bennylin** [sastrawi/sastrawi#15]
Saya coba mencari "melainkan" belum bisa mendapat kata dasarnya: "lain". Yang contoh lain adalah akhiran "-Ku", "-Mu", "-Nya" untuk Tuhan, seharusnya sederhana saja, tapi juga belum tertangkap. Apakah sudah dicoba dijalankan untuk satu korpus bahasa? Berapa persentase kesalahannya?

**Comment by andylibrian** [comment]
Hai @bennylin

Stemmer sastrawi termasuk jenis stemmer yang menggunakan kata dasar. Kata "melainkan" di sini setelah saya cek, masuk ke kata dasar. Padahal seharusnya tidak. Nanti akan saya hapus dari kata dasar.

Untuk akhiran -Ku, -Mu, -Nya ini memang belum masuk dalam pola yang distem. Bisa dicoba di stemmer lain, sepertinya juga tidak berhasil melakukan stem pada pola tersebut. Ini bisa menjadi bahan pengembangan juga.

:+1:

**Comment by bennylin** [comment]
wow, terima kasih untuk respons cepatnya :+1:

**Comment by andylibrian** [comment]
@bennylin,
Silakan dicoba lagi untuk issue ini, **melainkan** dan **-Ku**, **-Mu**, **-Nya** sudah distem di versi 1.0.9
