### ISSUE TITLE
Bagaimana cara mencari list stemming word nya

### ISSUE THREAD

**Issue by coder5** [sastrawi/sastrawi#17]
Misal kata input kata `tahun` maka akan muncul 
`menahun, bertahun-tahun, setahun`

**Comment by andylibrian** [comment]
Hai @coder5,

Stemming tidak digunakan untuk keperluan seperti itu. Saya juga belum menemukan library yang berfungsi demikian.

Kalau buat sendiri bisa dengan cara mengambil daftar kata dasar, lalu ditambahkan imbuhan satu per satu.

**Comment by coder5** [comment]
ok sip thanks bgt app ini kebantu banget buat saya 
btw klo stemming basa arab saya blun nemu mungkin ada info ?

**Comment by andylibrian** [comment]
Untuk arabic bisa dicari di sini : https://sites.google.com/site/nlp4arabic/

Terima kasih :)

**Comment by coder5** [comment]
anda bilang fungsi stemming ini memudahkan mencari kata dalam database 
misal saya cari kata `suara` namun di database ada kata `menyuarakan` maka tidak akan ketemu meski pake `LIKE %%` apakah saya harus bikin sistem stemming di seluruh database nya ?

**Comment by andylibrian** [comment]
Digunakan pada field tertentu saja yang dibutuhkan pada pencarian. Nanti kalau ada waktu luang, saya coba tulis tutorial tentang ini.

**Comment by coder5** [comment]
ya brati inti nya saya harus bikin stemming pada field tertentu ?
