### ISSUE TITLE
Kasus contoh

### ISSUE THREAD

**Issue by tommoholmes10** [sastrawi/sastrawi#18]
Gan bisa gak ini membuat seperti google. jadi misal kita mau mencari kisaran tahun. jadi nanti nya akan seperti ini
dari tanggal 19 september sampai 20 september akan jadi range antara 19 september sampai 20 september

**Comment by andylibrian** [comment]
seperti google gimana ya gan, bisa dijelaskan contoh outputnya?

**Comment by tommoholmes10** [comment]
Contoh nya kyk google convert mata uang gan
contoh nya
usd to rupiah

**Comment by andylibrian** [comment]
Bukan sejauh itu mas, stemmer / lemmatizer hanya berfungsi untuk mengubah kata berimbuhan menjadi kata dasarnya. Seperti:

Menambahkan -> tambah

**Comment by andylibrian** [comment]
Ditutup karena tidak ada perbincangan lebih lanjut.
