### ISSUE TITLE
Tanya : Referensi sastrawi

### ISSUE THREAD

**Issue by herpiko** [sastrawi/sastrawi#22]
Sastrawi memuat beberapa referensi penelitian, salah satunya : 

- Implementasi Modifikasi Enhanced Confix Stripping Stemmer Untuk Bahasa Indonesia dengan Metode Corpus Based Stemming

Namun hasil stemming sastrawi belum mencapai hasil yang dicapai oleh paper tersebut. Saya pikir baru sampai ECS. Apakah benar?

**Comment by andylibrian** [comment]
Hi @herpiko,

Pada penelitian yang dimaksud, halaman 8, Sastrawi mengimplementasikan stemming Sisipan (er, el, em, in), Serapan bahasa asing (-is, -isme, dst). Untuk Corpus Based Stemming, memang tidak diimplementasikan.

**Comment by herpiko** [comment]
@andylibrian Terima kasih atas konfirmasinya.

Halaman 12 pada penelitian tersebut, ada contoh-contoh bentuk stemming yang gagal di ECS dan diperbaiki (bukan corpus). Sayangnya tidak dijelaskan detail algo perbaikannya seperti apa.

Saya menguji sastrawi dengan KBBI yang strukturnya dibalik untuk mendapatkan bentuk [variasi kata dasar -> kata dasar]. Sebagian hasil uji (masih perlu dipilah-pilah lagi) :  http://pendekar.blankon.in/~piko/riset/

**Comment by herpiko** [comment]
>> Tertarik untuk berkontribusi menambahkan corpus based stemming?

Saya berniat memporting sastrawi ke Javascript agar bisa dipakai di lingkungan Node. :)

**Comment by andylibrian** [comment]
>    Saya menguji sastrawi dengan KBBI yang strukturnya dibalik untuk mendapatkan bentuk [variasi kata dasar -> kata dasar]. Sebagian hasil uji (masih perlu dipilah-pilah lagi)

Keren. Silakan dishare, barangkali bisa jadi PR, di mana orang bisa berkontribusi. Sebetulnya saya juga mengantongi beberapa kegagalan stemming pada kata-kata yang susah. Belum sempat mikirin solusinya.

>    Saya berniat memporting sastrawi ke Javascript agar bisa dipakai di lingkungan Node. :)

Luar biasa, nanti kabari saya alamat repo nya ya.

**Comment by herpiko** [comment]
Baik. Tiket ini saya tutup. Jika hasil uji tersebut sudah dikasifikasikan, saya buat tiket baru.

**Comment by herpiko** [comment]
FYI, https://github.com/ikhsanalatsary/akarata, written by @ikhsanalatsary. It passes against [reversed dictionary](https://raw.githubusercontent.com/herpiko/uji-sastrawi/master/reversed.json) that Sastrawi doesn't.

**Comment by andylibrian** [comment]
Terima kasih @herpiko saya lihat akarata mengimplementasikan algorithma Tala. Berbeda dengan Sastrawi yang berasal dari Nazief & Adriani.

Algoritma yang berasal dari Nazief & Adriani menggunakan kamus kata dasar, sedangkan algoritma Tala tanpa kamus kata dasar.

Saya sempat menulis tentang posisi Sastrawi saat ini : https://github.com/sastrawi/sastrawi/wiki/Stemming-Bahasa-Indonesia 

> Untuk menyelesaikan soal ini, proses stemming akan membutuhkan konteks yang lebih utuh. Sastrawi belum berencana akan ke arah sana, karena hal itu akan membuat library menjadi tidak sederhana lagi. Selain itu, akan dibutuhkan corpus, yang akan membuat instalasi library menjadi lebih rumit.
