### ISSUE TITLE
Saran dan Nambah

### ISSUE THREAD

**Issue by irsalshabirin** [sastrawi/sastrawi#23]
Library keren, sangat membantu :)
:+1: :+1: :+1: 
berikut untuk penambahan hasil dari uji coba yang saya lakukan di portal-portal berita Indonesia :
penyelidikan -> lidi (harusnya : selidik)
mengemasnya -> emas (harusnya : kemas)
berupa -> upa (harusnya : rupa)
perbankan -> perban (harusnya : perbankan, saya jg bingung)
senilai -> nila (harusnya : nilai)
mengasih -> asih (harusnya : kasih)
pergerakan -> gera (harusnya : gerak)
peradangan -> adang (harusnya : radang)
mengunjungi -> unjung (harusnya : kunjung)
memasuki -> pasuk (harusnya : masuk)
belasan -> bas (harusnya : belas)
berikan -> ikan (harusnya : beri)
mengecek -> ecek (harusnya : cek)
beraktifitas -> beraktifitas (harusnya : aktivitas)
berbasis -> bas (harusnya : basis)

ini untuk nama atau tempat yang juga terkena stemming :
susi -> sus (harusnya : susi)
bali -> bal (harusnya : bali)

mungkin saya bisa saran, ada 1 file txt yang berisi exception untuk outputnya. Agar output dari stemming bisa diatur lewat file txt tersebut.
Atau mungkin kita di readme nya ditambahkan untuk mengedit file .txt yang sudah tersedia pada library ini. Untuk menambah perbendaharaan kata nya.

Sekalian izin untuk digunakan dalam aplikasi thesis saya.
Terima kasih banyak :)

**Comment by andylibrian** [comment]
Hai @irsalshabirin terima kasih telah memberi masukan. Permasalahan pada stemming Bahasa Indonesia (bukan hanya Sastrawi, tapi library stemmer atau algoritma lain juga mengalami), memang belum semua diatasi. Saya menulisnya lebih rinci di https://github.com/sastrawi/sastrawi/wiki/Stemming-Bahasa-Indonesia, silakan dibaca untuk dapat lebih memahami situasi stemming dan posisi Sastrawi Stemmer.

Hampir semua kasus @irsalshabirin sudah terpetakan di tulisan saya tersebut. Silakan bila ada tanggapan.

Terima kasih.

**Comment by irsalshabirin** [comment]
siap mas. Sudah terjawab :+1: 
untuk saran saya yang 1 file .txt dijadikan exception bagaimana mas ?
Terima kasih :)

**Comment by andylibrian** [comment]
Oh iya,

>    mungkin saya bisa saran, ada 1 file txt yang berisi exception untuk outputnya. Agar output dari stemming bisa diatur lewat file txt tersebut.

Saya masih kurang yakin jika cara ini pas untuk dipasang pada library. Saya berpendapat exception adalah logika yang sangat sederhana, sehingga dapat diterapkan sendiri di luar library. Misalnya:

```php

// pengecualian berisi nama, bisa disimpan dalam file text
$pengecualian = ['susi', 'bali'];

if (isset($pengecualian[$kata])) {
    $stem = $pengecualian[$kata];
} else {
   $stem = $stemmer->stem($kata);
}
```

>    Atau mungkin kita di readme nya ditambahkan untuk mengedit file .txt yang sudah tersedia pada library ini. Untuk menambah perbendaharaan kata nya.

Ini ide bagus, saya akan tambahkan. Terima kasih.

**Comment by irsalshabirin** [comment]
sip mas, terima kasih banyak :+1: 
keren :+1: :100:

**Comment by andylibrian** [comment]
Mas @irsalshabirin,

Saya baru rilis [Sastrawi Stemmer v1.1.0](https://github.com/sastrawi/sastrawi/releases/tag/v1.1.0), sekarang sudah bisa menambah dan mengurangi kata dasar.
Silakan lihat pada https://github.com/sastrawi/sastrawi#penggunaan.

Untuk memperbarui versi bisa dilakukan dengan composer update. Silakan dicoba.

Terima kasih.

**Comment by irsalshabirin** [comment]
Keren mas :+1:  :+1:  :+1: 
Terima kasih :100:
