### ISSUE TITLE
sekedar masukan utk normalizeText

### ISSUE THREAD

**Issue by steamboatid** [sastrawi/sastrawi#24]
```
public static function normalizeText($text)
{
    $text = strtolower($text);
    // http://stackoverflow.com/questions/8304191/regex-to-add-spacing-between-sentences-in-a-string-in-php
    $text = preg_replace('/(?<!\.)\.(?!(\s|$|\,|\w\.))/', '. ', $text);
    //$text = preg_replace('/[^a-z0-9 -]/im', ' ', $text);
    $text = preg_replace('/( +)/im', ' ', $text);

    return trim($text);
}
```

dengan perubahan diatas, tanda baca kalimat masih ada.

**Comment by steamboatid** [comment]
$text = preg_replace('/([a-z0-9])([^a-z0-9 -])/im', '$1 $2 ', $text);

**Comment by steamboatid** [comment]
ralat:

`$text = preg_replace('/([a-z0-9])([^a-z0-9 -])/im', '$1 $2 ', $text);`

**Comment by andylibrian** [comment]
Terima kasih atas masukannya @steamboatid 

Sebetulnya, setelah proses pengembangan library ini, saya lebih condong kepada proses Stemming itu dilakukan per kata / token, bukan kepada kalimat. Jadi contoh di halaman readme perlu diupdate.

Sehingga tanda baca tidak perlu masuk ke dalam ruang lingkup stemming.
Secara lebih utuh proses nya kurang lebih seperti ini:

- Tokenization : memisahkan kalimat menjadi token / kata
- Stemming : tiap-tiap kata yang perlu distem, lakukan stemming.
