### ISSUE TITLE
Integrasi dengan Php biasa atau Native

### ISSUE THREAD

**Issue by damarajati** [sastrawi/sastrawi#25]
Minta tolong share library untuk Php biasa atau native dong mas, thanks expert!

**Comment by andylibrian** [comment]
Sastrawi menggunakan php biasa & native. Jika yang dimaksud adalah php procedural, tanpa OOP, bisa cari stemmer lain lewat google. Sastrawi tidak tersedia di php prosedural.

**Comment by damarajati** [comment]
iya mas maksud saya tolong contoh in penggunaan fungsinya tanpa harus menggunakan framework

**Comment by andylibrian** [comment]
Contoh yang ada di Readme itu tanpa framework mas. Apa sudah dicoba?

**Comment by damarajati** [comment]
lalu peletakan file demo.php nya yg required vendor itu dimana mas? maaf saya newbie juga di laravel :D

**Comment by andylibrian** [comment]
Pada contoh itu, file demo.php ada di directory project, di directory yang
sama dengan composer.json

**Comment by damarajati** [comment]
failed to open stream: No such file or directory vendor/autoload.php
eror mas :'D

**Comment by andylibrian** [comment]
Sudah lakukan langkah composer require?

**Comment by damarajati** [comment]
MAKASIH MAS!
