### ISSUE TITLE
Output menyertakan imbuhan

### ISSUE THREAD

**Issue by tomeroto** [sastrawi/sastrawi#34]
hi mas bro,

bisakah _output_ menyertakan imbuhan yang sudah di _delimiter_ dengan demikian kita tahu juga imbuhan yang digunakan, jadi bukan sekedar di _cut_ ;)

misalkan yang di stem kata: mempergunakan
maka _output_ yang terjadi misalkan dengan _delimiter_ '-', maka: mem-per-guna-kan

thanks atas bantuannya

**Comment by andylibrian** [comment]
Hi mas @tomeroto, tidak bisa di library ini. Hanya support stem / memotong.
