### ISSUE TITLE
Cara penggunaan di Laravel

### ISSUE THREAD

**Issue by alimuddinhasan** [sastrawi/sastrawi#38]
Cara penggunaannya gimana ya?

**Comment by ardianta** [comment]
Install pakai composer

<pre>php composer.phar require sastrawi/sastrawi:^1</pre>

Lihat sampel kodenya di [README.md](https://github.com/sastrawi/sastrawi/blob/master/README.md)

**Comment by alimuddinhasan** [comment]
Udah ane install gan, tapi pas penerapan di source code ini ada error message nya
```
<?php
// demo.php

// include composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// create stemmer
// cukup dijalankan sekali saja, biasanya didaftarkan di service container
$stemmerFactory = new \Sastrawi\Stemmer\StemmerFactory();
$stemmer  = $stemmerFactory->createStemmer();

// stem
$sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan';
$output   = $stemmer->stem($sentence);

echo $output . "\n";
// ekonomi indonesia sedang dalam tumbuh yang bangga

echo $stemmer->stem('Mereka meniru-nirukannya') . "\n";
// mereka tiru

```
Stemmer factory nya gak bisa, bisa minta tolong contoh penerapan di controllernya?

**Comment by ardianta** [comment]
@alimuddinhasan pesan errornya apa gan? 

di saya work kok!

<pre>
$ php demo.php 
ekonomi indonesia sedang dalam tumbuh yang bangga
mereka tiru
</pre>

**Comment by alimuddinhasan** [comment]
@ardianta 
Error nya kayak gini gan 

> FatalErrorException in StemmingController.php line 16:
> App\Http\Controllers\Analisis\StemmingController::index(): Failed opening required 'E:\xampp\htdocs\ta\app\Http\Controllers\Analisis/vendor/autoload.php' (include_path='E:\xampp\php\PEAR')

Ane bikin di controller seperti ini
```
<?php

namespace App\Http\Controllers\Analisis;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\KamusKataDasar;

class StemmingController extends Controller
{

    public function index()
    {
        require_once __DIR__ . '/vendor/autoload.php';

// create stemmer
// cukup dijalankan sekali saja, biasanya didaftarkan di service container
        $stemmerFactory = new \Sastrawi\Stemmer\StemmerFactory();
        $stemmer  = $stemmerFactory->createStemmer();

// stem
        $sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan';
        $output   = $stemmer->stem($sentence);

        echo $output . "\n";
// ekonomi indonesia sedang dalam tumbuh yang bangga

    }
}
```

instalasi pake **composer require sastrawi/sastrawi:^1**  udah, tapi pas dipake di controller jadinya error gitu, apa ada yang salah yaa?

**Comment by ardianta** [comment]
Itu masalah pada require-nya gan, salah alamat.

<pre><code class="php">require_once __DIR__ . '/vendor/autoload.php';</code></pre>

Coba matikan/komentari baris kode yang itu, apa hasilnya?

Kalau tidak salah, di Laravel sudah di-require otomatis.

**Comment by alimuddinhasan** [comment]
Muncul error gini gan pas tak ilangin

> FatalErrorException in StemmingController.php line 20:
> Class 'Sastrawi\Stemmer\StemmerFactory' not found

**Comment by ardianta** [comment]
Coba di-use dulu class-nya:

<pre><code class="php">use Sastrawi\Stemmer\StemmerFactory;</code></pre>

dan coba juga untuk _reload autoload_ dari composer:

<pre><code>> composer dump-autoload</code></code>

**Comment by ravimelann123** [comment]
$stemmerFactory = new \Sastrawi\Stemmer\StemmerFactory();
        $stemmer  = $stemmerFactory->createStemmer();

        // stem
        $sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan';
        $output   = $stemmer->stem($sentence);

        echo $output . "<br>";
        // ekonomi indonesia sedang dalam tumbuh yang bangga

        echo $stemmer->stem('Mereka meniru-nirukannya');
        // mereka tiru

ko saya malah muncul nya cuma 
perekonomian indonesia sedang dalam pertumbuhan yang membanggakan
mereka meniru-nirukannya
cuma berubah huruf kecil aja

**Comment by andylibrian** [comment]
@ravimelann123 coba check isi `composer.lock` lalu cari `sastrawi`. Versi berapa yang terinstall di sana?
