### ISSUE TITLE
Laravel 5.2 PHP 7 stemming tidak berjalan

### ISSUE THREAD

**Issue by alimuddinhasan** [sastrawi/sastrawi#39]
Sudah saya install dan tidak bisa melakukan stemming, kalimat yang keluar masih sama dengan yang berimbuhan

**Comment by andylibrian** [comment]
Tolong mereport error, dituliskan juga environmentnya:

- Operating System
- Versi PHP
- Bagaimana langkah-langkah mendapatkan error tersebut
