### ISSUE TITLE
Library tidak berjalan

### ISSUE THREAD

**Issue by andarpole** [sastrawi/sastrawi#40]
setelah beberapa kali dicoba, dari proses penginstalan sampai menjalankan test dapat berjalan. Tapi saat aplikasi dijalankan, output yang keluar tidak mengalami stemming.

Apakah ada yang mendapatkan masalah yang serupa?

**Comment by adamzul** [comment]
perlu ada sedikit perubahan di class ArrayDictionary.php .function addWorks bisa dirubah seperti berikut:

`public function addWords(array $words)`
`    {`
`        $words = preg_split("/[\s]+|-/", $words[0] );`
`        foreach ($words as $word) {`
`            $this->add($word);`
`        }`
`    }`

**Comment by andylibrian** [comment]
@adamzul bisa dijelaskan kenapa perlu diubah seperti itu? Saya belum mengerti masalahnya.

Tolong mereport error, dituliskan juga environmentnya:

- Operating System
- Versi PHP
- Bagaimana langkah-langkah mendapatkan error tersebut

**Comment by adamzul** [comment]
function aslinya kan seperti ini:

`public function addWords(array $words)`
`{`
`foreach ($words as $word) {`
`$this->add($word);`
`}`
`}`

masalahnya variable $words berbentuk ["ada apa ..."], sehingga ketika di foreach hanya terbaca sebagai 1 array. untuk itu perlu dipecah menjadi banyak array dengan preg_split(), sehingga bentuknya menjadi ["ada", "apa", ...].

masalah yg saya jumpai ini pada windows 7, php 5.6.24, dan saya menerapkan di framework symfony

**Comment by andylibrian** [comment]
Variable `$words` yang dimasukkan harusnya sudah berupa kata, bukan kalimat.

**Comment by andylibrian** [comment]
@andarpole masih belum bisa?
