### ISSUE TITLE
Sastrawi demo doesn't work?

### ISSUE THREAD

**Issue by leutwein** [sastrawi/sastrawi#42]
halo, saya baru saja membuka [demo site](http://sastrawi.github.io/) yang di sediakan
saya mencoba dengan contoh-contoh yang ada pada web. namun tidak ada yang berubah atau hasil stem yang keluar.

**Comment by ardianta** [comment]
Sepertinya server back-end lagi down

**Comment by andylibrian** [comment]
Betul, server demo tidak bekerja.
