### ISSUE TITLE
Sastrawi  not working in Laravel 5.5

### ISSUE THREAD

**Issue by ryukya** [sastrawi/sastrawi#43]
Maaf mengganggu saya sudah menginstal sastrawi di laravel menggunakan command "composer require sastrawi/sastrawi:^1
 Kemudian saya coba panggil di controller dengan kode berikut. Namun outputnya tetap sama.Ada yang tahu kenapa ?

INi Outputnya:
![sas](https://user-images.githubusercontent.com/11540064/34373827-dd2a3938-eb20-11e7-9c61-1898294c87b0.JPG)

`<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Auth;
use Illuminate\Http\Request;
use App\User;
use App\artik;
use App\Category;
use Sastrawi\Stemmer\StemmerFactory;
class UserController extends Controller
{ 
///......

 public function showPlagiForm(){

// create stemmer
// cukup dijalankan sekali saja, biasanya didaftarkan di service container
$stemmerFactory = new \Sastrawi\Stemmer\StemmerFactory();
$stemmer  = $stemmerFactory->createStemmer();

// stem
$sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan';
$output   = $stemmer->stem($sentence);

echo $output . "\n";
// ekonomi indonesia sedang dalam tumbuh yang bangga

echo $stemmer->stem('Mereka meniru-nirukannya') . "\n";
// mereka tiru

  //  return view('user.plagiForm');
    
   }
}`

**Comment by andarpole** [comment]
hal yang sama terjadi pada saya. kemudian saya putuskan untuk coba install 1 versi dibawahnya, dan bisa dipakai

**Comment by andylibrian** [comment]
Versi berapa yang bisa dipakai? Dan mulai versi berapa tidak bisa?

**Comment by ryukya** [comment]
versi 1.0 Pak yang tidak bisa..saya instal nya via composer.. langsung .sesuai dengan guidenya Pak.

**Comment by andylibrian** [comment]
versi terbaru 1.2, untuk mendapat versi baru, tuliskan seperti yg di README:

`sastrawi/sastrawi:^1`
