### ISSUE TITLE
Metode searching

### ISSUE THREAD

**Issue by tebuct** [sastrawi/sastrawi#44]
Untuk fungsi searching pada kamus, variabel yang menampung list kata-kata input dan kata-kata pada kamus yang mana ya? dan proses pencocokannya dibagian mana? terimakasih.

**Comment by andylibrian** [comment]
di https://github.com/sastrawi/sastrawi/blob/master/src/Sastrawi/Stemmer/Context/Context.php pada baris-basis `$this->dictionary->contains()`
