### ISSUE TITLE
Load Kata-dasar.txt salah, librari jadi tidak melakukan stemming

### ISSUE THREAD

**Issue by zawaruddin** [sastrawi/sastrawi#45]
library tidak jalan atau tidak melakukan stemming karena load data kata-dasar.txt tidak sesuai.
setelah di debug, return dari **function getWordsFromFile()** pada class **StemmerFactory**
adalah
```
Array
(
    [0] => aba
aba-aba
abad
abadi
abadiah
```

untuk memperbaiki ini bisa diganti bagian
`return explode(PHP_EOL, file_get_contents($dictionaryFile));`
menjadi
`return explode("\n", file_get_contents($dictionaryFile));`

hasilnya 
```
Array
(
    [0] => aba
    [1] => aba-aba
    [2] => abad
    [3] => abadi
    [4] => abadiah
    [5] => abah
    [6] => abah-abah
```

**Comment by andylibrian** [comment]
Hai mas @zawaruddin, versi berapa yang sedang digunakan? Karena bug yang direport di atas sudah lama dibetulkan, coba cek kode nya di branch master : https://github.com/sastrawi/sastrawi/blob/master/src/Sastrawi/Stemmer/StemmerFactory.php#L67

**Comment by zawaruddin** [comment]
versi 1, yang sesuai dengan panduan install via composer... 
[https://github.com/sastrawi/sastrawi#cara-install](https://github.com/sastrawi/sastrawi#cara-install)

**Comment by andylibrian** [comment]
Kalo sesuai dengan panduan itu, command nya seperti ini:

```
php composer.phar require sastrawi/sastrawi:^1
```

itu akan install versi major 1, dengan versi minor terbaru, yaitu saat ini (1.2.0)

Di tempat saya, kalau jalankan command di atas, muncul seperti ini:

```
$ php composer.phar require sastrawi/sastrawi:^1
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing sastrawi/sastrawi (v1.2.0): Loading from cache
Writing lock file
Generating autoload files

$ cat composer.json 
{
    "require": {
        "sastrawi/sastrawi": "^1"
    }
}
```

**Comment by andylibrian** [comment]
Issue ditutup karena tidak ada diskusi lebih lanjut.
