### ISSUE TITLE
Tambah Kata Dasar (Stemming) dan Tambah List Stopword

### ISSUE THREAD

**Issue by rizama** [sastrawi/sastrawi#47]
Assalamualaikum,,
saya ingin bertanya untuk menambahkan data Kata Dasar pada Stemming dan Kata Stopword bagaimana yah ? soalnya saya tambahkan pada file kata-dasar.txt itu sepertinya file di protect sehingga tidak bertambah, begitu pula dengan List Stopword. 

mohon pencerahannya.. 
Terimakasih

**Comment by andylibrian** [comment]
Wa'alaikumussalaam Warahmatullahi Wabarakatuh.

Untuk menambah kata dasar, sudah ada di readme, https://github.com/sastrawi/sastrawi cari bagian "Menambah dan Mengurangi Kata Dasar"

**Comment by andylibrian** [comment]
Issue ditutup karena sudah tidak ada diskusi lebih lanjut.
