### ISSUE TITLE
menggunakan algoritma stem apa ? 

### ISSUE THREAD

**Issue by jufianto** [sastrawi/sastrawi#49]
maaf saya sedikit bingung dengan penjelasan di README nya 
disana tertera beberapa algoritma seperti Enhanced Confix Stripping Stemmer dan Algoritma Nazief dan Adriani. 
apakah ini menggunakan kedua algortima tersebut ? atau salah satu algoritma yang dipakai ?

**Comment by andylibrian** [comment]
Algoritma ECS (Enhanced Confix Stripping) adalah penyempurnaan dari Algoritma CS (Confix Stripping), yang juga penyempurnaan dari Algoritma Nazief dan Adriani. Silakan dibaca lebih lanjut paper ECS.
