### ISSUE TITLE
StopWordRemover doesn't work

### ISSUE THREAD

**Issue by budihaa** [sastrawi/sastrawi#50]
Saya menggunakan stopword dan stopword tidak bekerja, ini script saya:

```
$stopwordsFactory = new \Sastrawi\StopWordRemover\StopWordRemoverFactory();
$stopwordsRemover = $stopwordsFactory->createStopWordRemover();
$output = $stopwordsRemover->remove($text);
```

Ketika $output saya print, masih mengandung kata "yang, dan, dll". Ada yang bisa bantu?
Terima Kasih.

**Comment by budihaa** [comment]
Ternyata setelah saya coba pada kalimat/teks biasa script diatas dapat bekerja. 

Namun jika kita menggunakan data/teks yang lebih banyak quantity-nya, stopword tersebut tidak bekerja secara maksimal (masih ada beberapa kata pada list stopword yang tertinggal)

**Comment by andylibrian** [comment]
Bisa tolong kasih contoh input nya?

**Comment by andylibrian** [comment]
Issue ditutup karena tidak ada komentar lebih lanjut
