### ISSUE TITLE
POS Taagging

### ISSUE THREAD

**Issue by faizalnurrozi** [sastrawi/sastrawi#53]
Gan numpang tanya, untuk project POS Taggingnya gk berlanjut ?
apakah ada kelemahan atau sudah di sempurnakan di project Sastrawi ?

**Comment by andylibrian** [comment]
Tidak berlanjut. Karena ide nya masih sama dengan algoritma yang sudah ada sekarang, menggunakan machine learning. Jadi jika ingin melakukan POS tagging, bisa menggunakan open source software yang sudah ada, kemudian latih modelnya.
