### ISSUE TITLE
Ga Work Sama sekali

### ISSUE THREAD

**Issue by abdurrahimi** [sastrawi/sastrawi#55]
kenapa ya gan, gabisa sama sekali, udah install pake composer. `composer require sastrawi/sastrawi:^1`

trus nyobain yang demo.php
tetep aja outputnya `Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan`

> <?php
// demo.php

// include composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// create stemmer
// cukup dijalankan sekali saja, biasanya didaftarkan di service container
$stemmerFactory = new \Sastrawi\Stemmer\StemmerFactory();
$stemmer  = $stemmerFactory->createStemmer();

// stem
$sentence = 'Perekonomian Indonesia sedang dalam pertumbuhan yang membanggakan';
$output   = $stemmer->stem($sentence);

echo $output . "\n";
// ekonomi indonesia sedang dalam tumbuh yang bangga

echo $stemmer->stem('Mereka meniru-nirukannya') . "\n";

**Comment by andylibrian** [comment]
Coba tulis di sini mas, isi dari `composer.json` atau `composer.lock`.

**Comment by haifahrul** [comment]
Hi @abdurrahimi

file `composer.json`
```php
{
    "require": {
        "sastrawi/sastrawi": "^1"
    }
}
```

Kemarin saya juga ada kendala.

**Laptop 1**
- OS Ubuntu 18.04 
- Server Nginx
- PHP 7.3
> ter stem dengan baik

**Laptop 2**
- OS Windows 10
- Server Nginx
- PHP 7.3
> stem tidak berjalan

Solusinya di `composer update`, dan baru berhasil di stem pada **Laptop 2**

**Comment by andylibrian** [comment]
Issue ditutup karena tidak ada komentar lebih lanjut, dan sepertinya sudah terselesaikan.
