### ISSUE TITLE
Bekasi di steam jadi bekas

### ISSUE THREAD

**Issue by mangcoding** [sastrawi/sastrawi#59]
apakah ada cara untuk mengexclude kata tertentu supaya tidak di steam. thanks

**Comment by andylibrian** [comment]
Ada 2 opsi mas:

1. Extend class Sastrawi\Stemmer atau buat fungsi baru, copy dari fungsi `Sastrawi\Stemmer::stem()`:

https://github.com/sastrawi/sastrawi/blob/09db1bda7756fae740767ed7eb8de1b01ae859d5/src/Sastrawi/Stemmer/Stemmer.php#L57-L69

Copy kode di atas ke fungsi baru, lalu tambahkan logic untuk exlude kata-kata tertentu:

```php
        $normalizedText = Filter\TextNormalizer::normalizeText($text);

        $words = explode(' ', $normalizedText);
        $stems = array();

        $excluded = ['bekasi'];

        foreach ($words as $word) {
            if (in_array($word, $excluded, true)) {   // <<-- exclude stemming
                $stems[] = $word;
            } else {
                $stems[] = $this->stemWord($word);
            }
        }

        return implode(' ', $stems);
```

2. Di Readme ada bagian `Menambah dan Mengurangi Kata Dasar`. Bisa coba ditambahkan di situ mas:

```php
$dictionary->add('bekasi');
```

**Comment by mangcoding** [comment]
baik mas terima kasih banyak, saya coba dulu. untuk yang pysastriwi sama aja kah? 
saya pake yang versi pythonnya

**Comment by andylibrian** [comment]
Pysastrawi beda author mas. Bisa coba tanya di sana langsung kalau spesifik yang versi python.

**Comment by mangcoding** [comment]
ok terima kasih mas, saya coba pull request nanti disana

**Comment by andylibrian** [comment]
Oke, saya tutup ya issue nya.  Terima kasih.
