### ISSUE TITLE
kata perancangan, pemrograman

### ISSUE THREAD

**Issue by DelvinWillian** [sastrawi/sastrawi#60]
ada beberapa kata yang tidak tepat stem nya. 
pemrograman => pemrograman
perancangan => ancang
Jika dikoding nya diedit seperti ini hasil nya sudah sesuai, namun apakah benar caranya? Terimakasih
![image](https://user-images.githubusercontent.com/17182046/103150549-de52a200-47a7-11eb-9b8d-2db2ff25b9a9.png)

**Comment by andylibrian** [comment]
@DelvinWillian Tidak tepat kalau kode Sastrawi diubah seperti itu. Untuk menambahkan kondisi disebutkan, lebih baik ditambahkan di sisi pengguna, seperti ini:

```php

if ($word == 'perancang') {
    $output = 'rancang';
} else if ($word == 'pemrograman') {
    $output = 'program';
} else {
    $output = $stemmer->stem($word);
}
```

**Comment by DelvinWillian** [comment]
baik pak @andylibrian, terimakasih atas sarannya
