### ISSUE TITLE
tidak bisa stemming di CI

### ISSUE THREAD

**Issue by amaliasr** [sastrawi/sastrawi#61]
mohon bantuannya saya sudah mengikuti arahan tetapi masih titdak bisa stemming atau kalimatnnya tidak berubah. terima kasih

**Comment by are-one** [comment]
Awal saat stemming tidak bekerja
`"sastrawi/sastrawi": "1"`

setelah saya ubah menjadi
`"sastrawi/sastrawi": "^1"`

stemming nya sudah bisa bekerja

**Comment by andylibrian** [comment]
Betul @are-one, seperti yang tertulis di readme, penyebutan versi perlu menggunakan character `^` (caret). https://getcomposer.org/doc/articles/versions.md
